language: php
php:
- '7.1'
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - composer self-update
before_scirpt:  
  - composer install
script: ./vendor/bin/phpunit --configuration phpunit.xml --coverage-text
