language: php
php:
- '5.6'
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - composer self-update
  - composer install
services:
  - mysql
script: phpunit --configuration phpunit.xml
